jwt.secret=your-256-bit-secret-key-make-it-very-long-and-secure-here
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/lab
spring.datasource.username=postgres
spring.datasource.password=lkroot
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# ===== ???????????? ??????? (??????????) =====
spring.datasource.replica.url=jdbc:postgresql://localhost:5432/lab_replica
spring.datasource.replica.username=rep_tester
spring.datasource.replica.password=rep_loot
spring.datasource.replica.driver-class-name=org.postgresql.Driver

# ?????????????? ????????? ??? ??????????
spring.datasource.replica.hikari.connection-timeout=30000
spring.datasource.replica.hikari.maximum-pool-size=5
spring.datasource.replica.hikari.read-only=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.default_schema=lab
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
