CREATE TABLE IF NOT EXISTS UserStatistic
(id BIGINT PRIMARY KEY REFERENCES Users(id) ON DELETE CASCADE,
reg_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
all_time INTERVAL DEFAULT '0',
avrg_time_day INTERVAL DEFAULT '0',
func_count INT DEFAULT 0);