CREATE TABLE IF NOT EXISTS UserStatistic
(id BIGINT PRIMARY KEY REFERENCES Users(id) ON DELETE CASCADE,
reg_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
avrg_time_day TIME DEFAULT 0,
func_count INT DEFAULT 0);